### ISSUE TITLE
Determine Case Study Candidates

### ISSUE THREAD

**Issue by DeniseHardman** [usergoodness/usergoodness.github.io#59]
research non-profits and/or businesses that we could complete a case study.

**Comment by timbroadwater** [comment]
Here are some thoughts that I have:

- [Hill Hounds](http://www.hillhounds.org/)
- [Pantry Plus More](https://www.pantryplusmore.org/)
- [The Gay & Lesbian Community Center of Pittsburgh](http://www.glccpgh.org/)

**Comment by kevikramer** [comment]
Nonprofit: Allegheny County Library - could be a very impactful study. They've been making updates to their site for the past few months (see https://librarycatalog.einetwork.net/Help/Changes), so they're at least interested and have the resources to make updates. But their site leaves a lot to be desired usability and content-wise. Seems like they have someone working on the site who knows little about UX.
https://aclalibraries.org/

Enterprise Software: ADP Vacation Logging - Kate uses this at work and says she almost always "gets it wrong". I can relate because our system at DSG is pretty terrible too. I'd reckon a lot of readers could relate. We can use her login for screenshots and obscure identifying information. Screenshot of software here: https://drive.google.com/open?id=1W-gDe12kHMAeQLcNrIwoh9nOmw4swfhg

B2C Business: Don't have one here yet, but would be cool to do something topical around the timeframe when we launch (eg The Winter Olympics site, if we were launching in Feb).

**Comment by DeniseHardman** [comment]
Non-profit
Hope Haven Farm
This is the animal sanctuary I was talking about in Pittsburgh. I imagine that Karen (who runs the farm) doesn't have any money to throw around for usability improvements. However, this could be a good case study (and photo op) to meet Karen and go out to the farm and take a look at what her vision is for the next few weeks and how we may tie that back to her digital presence and outreach strategy. This could be a good case study to show that we're not just a phone call and a few meetings, but we want to understand and experience through the lens of a supporter. 

Small Business
Edgar's Best Tacos
This is a slightly different approach for a case study. Edgar's Tacos used to have a small outdoor taco cart in The Strip. I think business has been good for them, because now they have a physical storefront a few blocks down from where they had the taco cart. Edgar's has a pretty decent Facebook following, so I know that there is a local presence with interest. The food scene in Pittsburgh is something that a lot of folks talk about. And you have a shop owner whose native tongue is Spanish, so that presents a unique case study in itself. Edgar's business model thrives on walk-in business as well as catering for events. Unfortunately, Edgar's website is lacking any type of user engagement to help support his walk-in business and catering services. What do customers want from Edgar's and how can we help position him to grow his business?

**Comment by zackpontious** [comment]
ridgway chamber of commerce - tourism site

**Comment by timbroadwater** [comment]
Hope Haven Farm and Pantry Plus More win!
